/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as FaviconDotsvgRouteImport } from './routes/favicon[.]svg'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchIndexDotjsonRouteImport } from './routes/search-index[.]json'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char123Char125DotmdRouteImport } from './routes/{$}[.]md'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsDocsSplatRouteImport } from './routes/_docs/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: '/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexDotjsonRoute = SearchIndexDotjsonRouteImport.update({
  id: '/search-index.json',
  path: '/search-index.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123Char125DotmdRoute = Char123Char125DotmdRouteImport.update({
  id: '/{$}.md',
  path: '/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocsSplatRoute = DocsDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/docs/$': typeof DocsDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/docs/$': typeof DocsDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/_docs': typeof DocsRouteWithChildren
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search-index.json': typeof SearchIndexDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{$}.md': typeof Char123Char125DotmdRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/_docs/docs/$': typeof DocsDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/favicon.svg'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/search-index.json'
    | '/sitemap.xml'
    | '/{$}.md'
    | '/docs/{$}.md'
    | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/favicon.svg'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/search-index.json'
    | '/sitemap.xml'
    | '/{$}.md'
    | '/docs/{$}.md'
    | '/docs/$'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/_docs'
    | '/favicon.svg'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/robots.txt'
    | '/search-index.json'
    | '/sitemap.xml'
    | '/{$}.md'
    | '/docs/{$}.md'
    | '/_docs/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  DocsRoute: typeof DocsRouteWithChildren
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchIndexDotjsonRoute: typeof SearchIndexDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char123Char125DotmdRoute: typeof Char123Char125DotmdRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.svg': {
      id: '/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-index.json': {
      id: '/search-index.json'
      path: '/search-index.json'
      fullPath: '/search-index.json'
      preLoaderRoute: typeof SearchIndexDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{$}.md': {
      id: '/{$}.md'
      path: '/{$}.md'
      fullPath: '/{$}.md'
      preLoaderRoute: typeof Char123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docs/docs/$': {
      id: '/_docs/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsDocsSplatRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsDocsSplatRoute: typeof DocsDocsSplatRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsSplatRoute: DocsDocsSplatRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  DocsRoute: DocsRouteWithChildren,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchIndexDotjsonRoute: SearchIndexDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char123Char125DotmdRoute: Char123Char125DotmdRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
